"""Kata cadangan agar setiap kanji punya kuota contoh 2 onyomi + 2 kunyomi.

Dipakai HANYA jika jukugo bab + kosakata seluruh bab belum menutupi kuota.
Klasifikasi on/kun dilakukan otomatis di `lib/kanji_examples.py`.
"""


def _w(word: str, kana: str, meaning: str) -> dict:
    return {"word": word, "kana": kana, "meaning": meaning}


FALLBACK_EXAMPLES: dict[str, list[dict]] = {
    "日": [_w("日", "ひ", "hari; matahari"), _w("日々", "ひび", "hari demi hari")],
    "私": [_w("私立", "しりつ", "swasta"), _w("私用", "しよう", "keperluan pribadi")],
    "会": [_w("会う", "あう", "bertemu"), _w("出会い", "であい", "perjumpaan")],
    "社": [_w("社長", "しゃちょう", "direktur"), _w("神社", "じんじゃ", "kuil Shinto")],
    "先": [_w("先", "さき", "ujung; lebih dulu"), _w("先ほど", "さきほど", "beberapa saat lalu")],
    "生": [_w("生きる", "いきる", "hidup"), _w("生まれる", "うまれる", "dilahirkan")],
    "学": [_w("学ぶ", "まなぶ", "mempelajari"), _w("学び", "まなび", "pembelajaran")],
    "書": [_w("書く", "かく", "menulis")],
    "新": [_w("新しい", "あたらしい", "baru")],
    "聞": [_w("新聞", "しんぶん", "surat kabar")],
    "語": [_w("語る", "かたる", "menceritakan"), _w("物語", "ものがたり", "cerita")],
    "上": [_w("上手", "じょうず", "pandai"), _w("上", "うえ", "atas")],
    "下": [_w("下", "した", "bawah")],
    "中": [_w("中", "なか", "dalam; tengah")],
    "国": [_w("国", "くに", "negara")],
    "円": [_w("円い", "まるい", "bulat")],
    "時": [_w("時", "とき", "waktu"), _w("時々", "ときどき", "kadang-kadang")],
    "分": [_w("分かる", "わかる", "mengerti")],
    "午": [_w("午前", "ごぜん", "pagi (AM)"), _w("午後", "ごご", "sore (PM)")],
    "毎": [_w("毎日", "まいにち", "setiap hari"), _w("毎週", "まいしゅう", "setiap pekan")],
    "休": [_w("休日", "きゅうじつ", "hari libur")],
    "働": [_w("労働", "ろうどう", "kerja; perburuhan"), _w("働く", "はたらく", "bekerja")],
    "来": [_w("来る", "くる", "datang")],
    "帰": [_w("帰国", "きこく", "pulang ke negara asal"), _w("帰る", "かえる", "pulang")],
    "電": [_w("電車", "でんしゃ", "kereta listrik"), _w("電話", "でんわ", "telepon")],
    "車": [_w("車", "くるま", "mobil")],
    "駅": [_w("駅員", "えきいん", "petugas stasiun"), _w("駅前", "えきまえ", "depan stasiun")],
    "飲": [_w("飲料", "いんりょう", "minuman"), _w("飲む", "のむ", "minum")],
    "読": [_w("読書", "どくしょ", "membaca buku"), _w("読む", "よむ", "membaca")],
    "見": [_w("見る", "みる", "melihat")],
    "買": [_w("売買", "ばいばい", "jual beli")],
    "水": [_w("水曜日", "すいようび", "hari Rabu"), _w("水", "みず", "air")],
    "花": [_w("花", "はな", "bunga")],
    "金": [_w("お金", "おかね", "uang")],
    "話": [_w("電話", "でんわ", "telepon"), _w("話す", "はなす", "berbicara")],
    "教": [_w("教える", "おしえる", "mengajar")],
    "貸": [_w("賃貸", "ちんたい", "sewa-menyewa"), _w("貸す", "かす", "meminjamkan")],
    "大": [_w("大きい", "おおきい", "besar")],
    "小": [_w("小さい", "ちいさい", "kecil")],
    "高": [_w("高校", "こうこう", "SMA"), _w("高い", "たかい", "tinggi; mahal")],
    "安": [_w("安全", "あんぜん", "keamanan"), _w("安い", "やすい", "murah")],
    "古": [_w("古代", "こだい", "zaman kuno"), _w("古い", "ふるい", "lama; tua")],
    "元": [_w("元", "もと", "asal"), _w("元々", "もともと", "sejak awal")],
    "好": [_w("好物", "こうぶつ", "makanan favorit"), _w("好きだ", "すきだ", "suka")],
    "間": [_w("間", "あいだ", "antara"), _w("間に合う", "まにあう", "tepat waktu")],
    "少": [_w("少女", "しょうじょ", "anak perempuan"), _w("少ない", "すくない", "sedikit")],
    "音": [_w("音", "おと", "bunyi"), _w("足音", "あしおと", "suara langkah")],
    "楽": [_w("音楽", "おんがく", "musik"), _w("楽しい", "たのしい", "menyenangkan")],
    "料": [_w("料理", "りょうり", "masakan"), _w("料金", "りょうきん", "biaya")],
    "前": [_w("前", "まえ", "depan; sebelum")],
    "後": [_w("午後", "ごご", "sore"), _w("後ろ", "うしろ", "belakang")],
    "右": [_w("左右", "さゆう", "kanan dan kiri"), _w("右", "みぎ", "kanan")],
    "左": [_w("左", "ひだり", "kiri")],
    "近": [_w("近所", "きんじょ", "sekitar rumah"), _w("近い", "ちかい", "dekat")],
    "台": [_w("台所", "だいどころ", "dapur"), _w("一台", "いちだい", "satu unit (mesin)")],
    "週": [_w("週末", "しゅうまつ", "akhir pekan"), _w("毎週", "まいしゅう", "setiap pekan")],
    "子": [_w("子", "こ", "anak"), _w("子供", "こども", "anak-anak")],
    "雨": [_w("雨", "あめ", "hujan")],
    "天": [_w("天気", "てんき", "cuaca"), _w("天国", "てんごく", "surga")],
    "気": [_w("気持ち", "きもち", "perasaan")],
    "暑": [_w("残暑", "ざんしょ", "sisa panas musim panas"), _w("暑い", "あつい", "panas (udara)")],
    "寒": [_w("寒冷", "かんれい", "dingin (iklim)"), _w("寒い", "さむい", "dingin")],
    "旅": [_w("旅", "たび", "perjalanan"), _w("一人旅", "ひとりたび", "bepergian sendiri")],
    "海": [_w("海外", "かいがい", "luar negeri"), _w("海", "うみ", "laut")],
    "事": [_w("事", "こと", "hal"), _w("出来事", "できごと", "peristiwa")],
    "公": [_w("公園", "こうえん", "taman"), _w("公立", "こうりつ", "milik negara")],
    "園": [_w("公園", "こうえん", "taman"), _w("動物園", "どうぶつえん", "kebun binatang")],
    "待": [_w("期待", "きたい", "harapan"), _w("待つ", "まつ", "menunggu")],
    "名": [_w("名前", "なまえ", "nama"), _w("名", "な", "nama")],
    "住": [_w("住所", "じゅうしょ", "alamat")],
    "開": [_w("開ける", "あける", "membuka")],
    "閉": [_w("閉店", "へいてん", "toko tutup"), _w("閉める", "しめる", "menutup")],
    "知": [_w("知識", "ちしき", "pengetahuan")],
    "持": [_w("所持", "しょじ", "kepemilikan")],
    "使": [_w("使用", "しよう", "penggunaan"), _w("使う", "つかう", "memakai")],
    "写": [_w("写真", "しゃしん", "foto"), _w("写す", "うつす", "menyalin")],
    "真": [_w("真ん中", "まんなか", "tengah-tengah"), _w("真っ白", "まっしろ", "putih bersih")],
    "乗": [_w("乗車", "じょうしゃ", "naik kendaraan")],
    "降": [_w("降車", "こうしゃ", "turun dari kendaraan"), _w("降りる", "おりる", "turun")],
    "長": [_w("社長", "しゃちょう", "direktur"), _w("長い", "ながい", "panjang")],
    "広": [_w("広告", "こうこく", "iklan"), _w("広い", "ひろい", "luas")],
    "番": [_w("番号", "ばんごう", "nomor"), _w("一番", "いちばん", "nomor satu; paling")],
    "医": [_w("医者", "いしゃ", "dokter"), _w("医院", "いいん", "klinik")],
    "者": [_w("若者", "わかもの", "kaum muda"), _w("何者", "なにもの", "orang macam apa")],
    "病": [_w("病む", "やむ", "menderita sakit"), _w("病", "やまい", "penyakit")],
    "院": [_w("病院", "びょういん", "rumah sakit"), _w("大学院", "だいがくいん", "pascasarjana")],
    "薬": [_w("薬局", "やっきょく", "apotek"), _w("薬", "くすり", "obat")],
    "切": [_w("切る", "きる", "memotong")],
    "作": [_w("作文", "さくぶん", "karangan"), _w("作る", "つくる", "membuat")],
    "歌": [_w("歌手", "かしゅ", "penyanyi")],
    "運": [_w("運ぶ", "はこぶ", "mengangkut")],
    "転": [_w("転ぶ", "ころぶ", "terjatuh")],
    "洗": [_w("洗濯", "せんたく", "mencuci pakaian")],
    "山": [_w("山", "やま", "gunung")],
    "登": [_w("登山", "とざん", "mendaki gunung"), _w("登る", "のぼる", "menaiki")],
    "練": [_w("練習", "れんしゅう", "latihan"), _w("訓練", "くんれん", "pelatihan")],
    "習": [_w("学習", "がくしゅう", "pembelajaran")],
    "馬": [_w("馬車", "ばしゃ", "kereta kuda"), _w("馬", "うま", "kuda")],
    "夏": [_w("夏季", "かき", "musim panas (istilah)"), _w("初夏", "しょか", "awal musim panas")],
    "春": [_w("春季", "しゅんき", "musim semi (istilah)"), _w("春分", "しゅんぶん", "ekuinoks musim semi")],
    "秋": [_w("秋分", "しゅうぶん", "ekuinoks musim gugur"), _w("秋", "あき", "musim gugur")],
    "冬": [_w("冬季", "とうき", "musim dingin (istilah)"), _w("冬眠", "とうみん", "hibernasi")],
    "思": [_w("思考", "しこう", "pemikiran")],
    "言": [_w("言語", "げんご", "bahasa"), _w("言う", "いう", "berkata")],
    "問": [_w("問う", "とう", "menanyakan"), _w("問い", "とい", "pertanyaan")],
    "題": [_w("問題", "もんだい", "masalah; soal"), _w("話題", "わだい", "topik")],
    "意": [_w("意味", "いみ", "arti"), _w("注意", "ちゅうい", "perhatian")],
    "着": [_w("到着", "とうちゃく", "kedatangan")],
    "洋": [_w("洋服", "ようふく", "pakaian gaya Barat"), _w("太平洋", "たいへいよう", "Samudra Pasifik")],
    "服": [_w("洋服", "ようふく", "pakaian gaya Barat"), _w("服装", "ふくそう", "cara berpakaian")],
    "約": [_w("約束", "やくそく", "janji"), _w("予約", "よやく", "reservasi")],
    "束": [_w("束", "たば", "ikat; berkas"), _w("花束", "はなたば", "buket bunga")],
    "道": [_w("道", "みち", "jalan")],
    "橋": [_w("歩道橋", "ほどうきょう", "jembatan penyeberangan"), _w("橋", "はし", "jembatan")],
    "角": [_w("三角", "さんかく", "segitiga"), _w("角", "かど", "sudut; tikungan")],
    "交": [_w("交わる", "まじわる", "bersilangan"), _w("交通", "こうつう", "lalu lintas")],
    "通": [_w("交通", "こうつう", "lalu lintas"), _w("通る", "とおる", "melewati")],
    "送": [_w("送別", "そうべつ", "perpisahan"), _w("送る", "おくる", "mengirim; mengantar")],
    "地": [_w("地図", "ちず", "peta"), _w("地下鉄", "ちかてつ", "kereta bawah tanah")],
    "図": [_w("地図", "ちず", "peta"), _w("図書館", "としょかん", "perpustakaan")],
    "紹": [_w("紹介", "しょうかい", "perkenalan")],
    "説": [_w("説く", "とく", "menguraikan")],
    "考": [_w("参考", "さんこう", "acuan"), _w("考える", "かんがえる", "berpikir")],
    "文": [_w("文化", "ぶんか", "budaya"), _w("文字", "もじ", "huruf")],
    "化": [_w("文化", "ぶんか", "budaya"), _w("変化", "へんか", "perubahan")],
    "活": [_w("生活", "せいかつ", "kehidupan"), _w("活動", "かつどう", "kegiatan")],
    "本": [_w("本", "ほん", "buku"), _w("本屋", "ほんや", "toko buku")],
}


# Tambahan agar setiap kanji pasti mencapai 4 contoh (kuota 2 on + 2 kun bila memungkinkan).
_EXTRA: dict[str, list[dict]] = {
    "新": [_w("新幹線", "しんかんせん", "Shinkansen"), _w("新たな", "あらたな", "yang baru")],
    "聞": [_w("見聞", "けんぶん", "pengalaman melihat-mendengar"), _w("聞こえる", "きこえる", "terdengar")],
    "上": [_w("上昇", "じょうしょう", "kenaikan"), _w("上がる", "あがる", "naik")],
    "下": [_w("下がる", "さがる", "menurun")],
    "円": [_w("円形", "えんけい", "bentuk bundar")],
    "午": [_w("正午", "しょうご", "tengah hari"), _w("午前中", "ごぜんちゅう", "sepanjang pagi")],
    "毎": [_w("毎年", "まいとし", "setiap tahun")],
    "働": [_w("労働者", "ろうどうしゃ", "pekerja; buruh")],
    "帰": [_w("帰宅", "きたく", "pulang ke rumah")],
    "電": [_w("電池", "でんち", "baterai")],
    "駅": [_w("駅長", "えきちょう", "kepala stasiun")],
    "読": [_w("音読", "おんどく", "membaca bersuara")],
    "買": [_w("買い手", "かいて", "pembeli")],
    "水": [_w("水道", "すいどう", "air keran"), _w("水着", "みずぎ", "baju renang")],
    "花": [_w("生花", "せいか", "seni merangkai bunga")],
    "金": [_w("金庫", "きんこ", "lemari besi")],
    "話": [_w("会話", "かいわ", "percakapan")],
    "小": [_w("小川", "おがわ", "sungai kecil")],
    "高": [_w("最高", "さいこう", "tertinggi; terbaik"), _w("高さ", "たかさ", "ketinggian")],
    "安": [_w("安売り", "やすうり", "obral")],
    "古": [_w("古着", "ふるぎ", "pakaian bekas")],
    "楽": [_w("楽器", "がっき", "alat musik"), _w("楽しむ", "たのしむ", "menikmati")],
    "料": [_w("無料", "むりょう", "gratis")],
    "後": [_w("最後", "さいご", "terakhir"), _w("後", "あと", "sesudah")],
    "右": [_w("右折", "うせつ", "berbelok kanan"), _w("右手", "みぎて", "tangan kanan")],
    "左": [_w("左折", "さぜつ", "berbelok kiri")],
    "雨": [_w("雨降り", "あめふり", "turun hujan")],
    "天": [_w("天才", "てんさい", "jenius"), _w("天体", "てんたい", "benda langit")],
    "暑": [_w("暑さ", "あつさ", "hawa panas")],
    "寒": [_w("寒さ", "さむさ", "hawa dingin")],
    "海": [_w("海洋", "かいよう", "kelautan"), _w("海辺", "うみべ", "tepi laut")],
    "公": [_w("公共", "こうきょう", "publik")],
    "園": [_w("幼稚園", "ようちえん", "taman kanak-kanak"), _w("学園", "がくえん", "kampus; sekolah")],
    "待": [_w("待機", "たいき", "bersiaga")],
    "名": [_w("氏名", "しめい", "nama lengkap")],
    "住": [_w("住民", "じゅうみん", "penduduk")],
    "閉": [_w("閉会", "へいかい", "penutupan acara")],
    "知": [_w("通知", "つうち", "pemberitahuan")],
    "使": [_w("大使館", "たいしかん", "kedutaan besar")],
    "写": [_w("複写", "ふくしゃ", "fotokopi")],
    "乗": [_w("乗客", "じょうきゃく", "penumpang")],
    "長": [_w("長所", "ちょうしょ", "kelebihan"), _w("長さ", "ながさ", "panjang (ukuran)")],
    "広": [_w("広大", "こうだい", "sangat luas"), _w("広場", "ひろば", "lapangan")],
    "医": [_w("医療", "いりょう", "layanan medis")],
    "院": [_w("入院", "にゅういん", "rawat inap"), _w("退院", "たいいん", "keluar dari rumah sakit")],
    "薬": [_w("薬品", "やくひん", "bahan obat"), _w("薬屋", "くすりや", "toko obat")],
    "作": [_w("作品", "さくひん", "karya")],
    "歌": [_w("国歌", "こっか", "lagu kebangsaan")],
    "山": [_w("山道", "やまみち", "jalan gunung")],
    "登": [_w("登録", "とうろく", "registrasi")],
    "練": [_w("熟練", "じゅくれん", "keahlian")],
    "馬": [_w("馬力", "ばりき", "tenaga kuda")],
    "秋": [_w("秋季", "しゅうき", "musim gugur (istilah)"), _w("秋晴れ", "あきばれ", "cerah musim gugur")],
    "言": [_w("発言", "はつげん", "pernyataan")],
    "題": [_w("題名", "だいめい", "judul")],
    "意": [_w("意志", "いし", "kemauan")],
    "着": [_w("着席", "ちゃくせき", "duduk di tempat")],
    "洋": [_w("洋室", "ようしつ", "kamar gaya Barat"), _w("西洋", "せいよう", "dunia Barat")],
    "服": [_w("制服", "せいふく", "seragam"), _w("和服", "わふく", "pakaian tradisional Jepang")],
    "約": [_w("約", "やく", "kira-kira"), _w("契約", "けいやく", "kontrak")],
    "束": [_w("結束", "けっそく", "kekompakan")],
    "道": [_w("水道", "すいどう", "air keran")],
    "橋": [_w("鉄橋", "てっきょう", "jembatan besi"), _w("橋渡し", "はしわたし", "perantara")],
    "角": [_w("角度", "かくど", "besar sudut"), _w("街角", "まちかど", "sudut jalan")],
    "通": [_w("通学", "つうがく", "pergi ke sekolah")],
    "地": [_w("土地", "とち", "tanah; lahan")],
    "図": [_w("図面", "ずめん", "gambar teknik"), _w("意図", "いと", "maksud")],
    "紹": [_w("自己紹介", "じこしょうかい", "perkenalan diri"), _w("紹介状", "しょうかいじょう", "surat pengantar")],
    "考": [_w("考慮", "こうりょ", "pertimbangan")],
    "化": [_w("化学", "かがく", "ilmu kimia"), _w("国際化", "こくさいか", "internasionalisasi")],
    "活": [_w("活用", "かつよう", "konjugasi; pemanfaatan"), _w("部活", "ぶかつ", "kegiatan klub")],
}

for _char, _words in _EXTRA.items():
    FALLBACK_EXAMPLES.setdefault(_char, []).extend(_words)
